spring:
  application:
    name: robot-fleet-management
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

mqtt:
  broker-url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  client-id: ${HOSTNAME:fleet-backend}

  topics:
    robot-status: robots/+/status
    robot-command: robots/%s/commands

  qos: 1
  clean-session: false